[package]
name = "gandi-ipv6-updater"
version = "0.1.0"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dotenvs = "0.1.0"
local-ip-address = "0.6.3"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
