[package]
name = "gandi-ipv6-updater"
version = "0.1.0"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dotenvs = "0.1.0"
local-ip-address = "0.5.4"
reqwest = "0.11.19"
tokio = { version = "1.32.0", features = ["full"] }
